#ifndef _TREFLECTION_INDEX_H_
#define _TREFLECTION_INDEX_H_

enum
{
    REFLECTION_INDEX = 1000,
    REFLECTION_INDEX_SPLINE_RED_GRP,
    REFLECTION_INDEX_SPLINE_RED_NUM_POINTS,
    REFLECTION_INDEX_SPLINE_RED,

    REFLECTION_INDEX_SPLINE_GREEN_GRP,
    REFLECTION_INDEX_SPLINE_GREEN_NUM_POINTS,
    REFLECTION_INDEX_SPLINE_GREEN,

    REFLECTION_INDEX_SPLINE_BLUE_GRP,
    REFLECTION_INDEX_SPLINE_BLUE_NUM_POINTS,
    REFLECTION_INDEX_SPLINE_BLUE,

    REFLECTION_INDEX_TEXT,
    
    ID_CREATE,

    METALTYPE,
    ALUMINIUM,
    OR,
}

#endif