CONTAINER TREFLECTION_INDEX
{
	NAME REFLECTION_INDEX;
    INCLUDE Texpression;

    GROUP ID_TAGPROPERTIES
	{
		LONG METALTYPE
		{
		    CYCLE
		    {
		        ALUMINIUM;
		        OR;
		    }
		}

		SEPARATOR { LINE; }	
		GROUP REFLECTION_INDEX_SPLINE_RED_GRP
		{
			LONG REFLECTION_INDEX_SPLINE_RED_NUM_POINTS { MIN 2; STEP 1; MINSLIDER 2; MAXSLIDER 100; CUSTOMGUI LONGSLIDER; }
			SPLINE REFLECTION_INDEX_SPLINE_RED { }
		}
		
		GROUP REFLECTION_INDEX_SPLINE_GREEN_GRP
		{
			LONG REFLECTION_INDEX_SPLINE_GREEN_NUM_POINTS { MIN 2; STEP 1; MINSLIDER 2; MAXSLIDER 100; CUSTOMGUI LONGSLIDER; }
			SPLINE REFLECTION_INDEX_SPLINE_GREEN { }
		}

		GROUP REFLECTION_INDEX_SPLINE_BLUE_GRP
		{
			LONG REFLECTION_INDEX_SPLINE_BLUE_NUM_POINTS { MIN 2; STEP 1; MINSLIDER 2; MAXSLIDER 100; CUSTOMGUI LONGSLIDER; }
			SPLINE REFLECTION_INDEX_SPLINE_BLUE { }
		}
		STATICTEXT REFLECTION_INDEX_TEXT { }
	}

    GROUP ID_CREATE
	{
		SPLINE REFLECTION_INDEX_SPLINE_RED { }
		SEPARATOR { LINE; }	
		SPLINE REFLECTION_INDEX_SPLINE_GREEN { }
		SEPARATOR { LINE; }	
		SPLINE REFLECTION_INDEX_SPLINE_BLUE { }
		SEPARATOR { LINE; }	
		STATICTEXT REFLECTION_INDEX_TEXT { }
	}
}