class Const():
    """
    Class for hold all our constant used in our plugin
    """
    PLUGIN_ID = 1037819
    VERSION = 1.2

    X_INVERTED = 1
    Y_INVERTED = 2

    UI_GROUP_CURVE = 0
    UI_GROUP_CURVE_METAL_TYPE = 1
    UI_GROUP_CURVE_RED = 2
    UI_GROUP_CURVE_GREEN = 3
    UI_GROUP_CURVE_BLUE = 4
    UI_GROUP_RGB = 5
    UI_GROUP_CREATE = 6

    UI_CYCLE = 0

    UI_BUTTON_REFRESH = 0
    UI_BUTTON_DELETE = 1
    UI_BUTTON_CREATE = 2

    UI_SPLINE_RED = 0
    UI_SPLINE_GREEN = 1
    UI_SPLINE_BLUE = 2

    UI_GRADIENT_RED = 0
    UI_GRADIENT_GREEN = 1
    UI_GRADIENT_BLUE = 2
    UI_GRADIENT_RGB = 3


    UI_SLIDER_RED = 0
    UI_SLIDER_GREEN = 1
    UI_SLIDER_BLUE = 2
    UI_SLIDER_RGB = 3

    UI_BOOL_RED_X = 0
    UI_BOOL_GREEN_X = 1
    UI_BOOL_BLUE_X = 2
    UI_BOOL_RED_Y = 3
    UI_BOOL_GREEN_Y = 4
    UI_BOOL_BLUE_Y = 5

    UI_STR_MAT_NAME = 0
    UI_STR_RED_K = 1
    UI_STR_RED_N = 2
    UI_STR_GREEN_K = 3
    UI_STR_GREEN_N = 4
    UI_STR_BLUE_K = 5
    UI_STR_BLUE_N = 6

    UI_SEPARATOR_RED = 0
    UI_SEPARATOR_GREEN = 1
    UI_SEPARATOR_BLUE = 2